version: '3'

services:
  minio:
    image: minio/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./data:/data
    environment:
      MINIO_ROOT_USER: $MINIO_ROOT_USER
      MINIO_ROOT_PASSWORD: $MINIO_ROOT_PASSWORD
    command: server /data --console-address :9001
    restart: always

  create-bucket:
    image: minio/mc:latest
    depends_on:
      - minio
    environment:
      MC_HOST_minio: http://${MINIO_ROOT_USER}:${MINIO_ROOT_PASSWORD}@minio:9000
    entrypoint:
      - sh
      - -c
      - |
        while ! curl -I http://minio:9000/minio/health/live; do echo 'Wait minio to startup...' && sleep 0.1; done; sleep 5;

        mc alias set $MINIO_ALIAS http://minio:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD
        mc admin user add $MINIO_ALIAS $MINIO_USER $MINIO_PASSWORD
        mc admin policy info $MINIO_ALIAS readwrite --policy-file /tmp/policy.json
        mc admin user svcacct add --access-key $AWS_ACCESS_KEY --secret-key $AWS_SECRET_KEY --policy "/tmp/policy.json" $MINIO_ALIAS $MINIO_USER
        mc rb --force $MINIO_ALIAS/$AWS_BUCKET
        mc mb $MINIO_ALIAS/$AWS_BUCKET
        mc anonymous set download $MINIO_ALIAS/$AWS_BUCKET